spring.application.name=BarbershopApp

spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/barbershop_app
spring.datasource.username = root
spring.datasource.password =

#spring.jpa.hibernate.hbl2ddl - to je ova ispod
spring.jpa.hibernate.ddl-auto = update

spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
#Postavljane dijalekta

# spring.jpa.hibernate.ddl-auto = create-drop
# koristi jedino ako napravis neku promjenu u entitetima pa zelis nove tabele.